.github/workflows/deploy.yaml
Continous deployment to Google Cloud
=> Continuous Deployment

src/controllers/auth/login.ts, src/controllers/auth/register.ts, src/controllers/auth/types.ts, src/controllers/auth/utils.ts, src/controllers/profile/get.ts, src/middleware/auth.ts, src/routes/auth.ts, src/routes/index.ts, src/routes/profile.ts
- Fixed the login and onboarding endpoints
- Refactored some functions to make them more reusable
=> Fixed login, onboarding endpoints and refactored a lot of routes.

.github/workflows/test-pr.yaml, src/config/firebase.ts
- Made changes to use new backend .env file.
- added test-pr.yaml workflow to build docker images on pull requests.
- Requires a new environment called "testing" that has access to the same secrets as production.
=> Build Docker image on PR workflow

src/controllers/payments/create.ts, src/routes/payments.ts
- Fix event payment, convert from dollars to cents to make stripe work
=> Fix event payment, convert from dollars to cents to make stripe work

src/controllers/events/attendee.ts, src/routes/event.ts
- if maxAttendee is -1, we will not have max capacity. Hence, we disabled the capacity check and it will return an error saying that the event is full.
- Updated addAttendee to check for this condition.
=> added remove cap check to check if maxAttendee is -1

src/controllers/events/attendee.ts, src/routes/event.ts, src/schema/Event.ts
- Edited the check in addAttendee to include event.isDisabled for capacity checking. Minor conflict with remove cap check PR.
- Added a new var isDisabled whenever new event is created. It will always be 'false' when event is newly created.
- Refactored check for required fields to include loops.
=> Added isDisabled in the event schema for execs to manually open or close events 

.github/workflows/deploy-staging.yaml, src/config/firebase.ts, src/controllers/events/attendee.ts, src/routes/event.ts, src/routes/payments.ts, src/schema/Event.ts
Major Features:
- Enabling Stripe Payment
- Improving attendee capacity check
=> Deployment 2024/11/11

src/routes/attendee.ts, src/routes/event.ts, src/schema/Event.ts, src/schema/Transaction.ts
- Created a single `/events/registered` that handles adding attendee and adding transactions.
- Also fixed some type issues.
=> Refactored payment and transactions flow.

src/controllers/auth/users.ts, src/routes/auth.ts
Creating a new API to retrieve all members for membership verification
Future to do: incorporate role-based access control for this so that we can prepare for Admin pages
=> Implement All User Display

.github/workflows/deploy-staging.yaml, src/config/firebase.ts, src/controllers/auth/users.ts, src/controllers/events/attendee.ts, src/routes/attendee.ts, src/routes/auth.ts, src/routes/event.ts, src/routes/payments.ts, src/schema/Event.ts
Major Features:
- Add new API for Internal Membership List Display
=> Deployment 2024/11/16

src/controllers/auth/register.ts, src/controllers/auth/types.ts, src/routes/auth.ts
- Renamed /onboarding endpoint to /onboard
- Refactored endpoint to also receive a paymentInfo object containing details of the member's Stripe payment.
- After adding user to database, add their transaction object.
- Added some new types for the changes above.
=> Refactored membership payment flow. Fixed missing member_id bug

.github/workflows/deploy-staging.yaml, .github/workflows/deploy.yaml, src/controllers/events/event.ts, src/routes/event.ts, src/schema/Event.ts, src/schema/EventForm.ts, src/utils/files.ts
=> Backend change to support custom form

src/controllers/emails/send.ts, src/routes/attendee.ts
- Create endpoint for fetching attendees based on event
=> Event registration flow feedback (2025/01/02)

.gcloudignore, .github/workflows/deploy.yaml, Dockerfile, src/config/firebase.ts, src/routes/auth.ts
=> Sync staging with main (2025/01/19)

src/controllers/auth/types.ts, src/controllers/auth/users.ts, src/routes/admin.ts, src/routes/index.ts
- **added admin route**
- **admin rout**
- Implemented endpoints for getting users for admin portal. These endpoints should not be accessible from our current membership portal
- admin portal frontend still WIP.
=> Implement users endpoints for admin

src/controllers/auth/types.ts, src/controllers/auth/users.ts, src/routes/admin.ts, src/routes/index.ts
- bring admin endpoint to prod
- new endpoints to get all users or get a specific user
=> Implement users endpoint for admin

.github/workflows/deploy-staging.yaml, .github/workflows/deploy.yaml, src/index.ts
- Update workflow files
- Add prod admin portal origin
- pushes to main automatically go to staging. Must run workflow manually for prod
- Add new allowed origin
=> Update workflows and add admin portal origin

.github/workflows/deploy-staging.yaml
- **fix workflow**
- **fix**
- **fix**
- **fix**
=> fix staging workflow

.github/workflows/deploy-staging.yaml, .github/workflows/deploy.yaml, package-lock.json, package.json, src/config/supabase.ts, src/routes/admin.ts, src/services/auth/users.ts
- supabase user endpoint created
=> supabase user endpoint

.github/workflows/deploy-staging.yaml, .github/workflows/deploy.yaml, src/config/stripe.ts, src/index.ts, src/routes/v2/index.ts, src/routes/v2/stripe.ts, src/routes/v2/webhookRouter.ts
Resolves #62
- Added webhook handler to handle Stripe webhooks
- Currently logs customer.created events to the console for testing
To test locally with the Stripe CLI:
- Run `stripe listen --forward-to localhost:8000/webhook` to listen to stripe webhooks
- Add webhook secret to .env as `STRIPE_WEBHOOK_SECRET`
- Use `stripe trigger [event name]` (ex. `stripe trigger customer.created`) to trigger events
=> Added stripe webhook endpoint

src/routes/v2/attendee.ts, src/routes/v2/event.ts, src/schema/v1/User.ts, src/services/auth/register.ts, src/services/auth/users.ts, src/services/auth/utils.ts, src/services/events/attendee.ts, src/services/events/event.ts, tests/services/auth/register.test.ts, tests/services/events/attendee.test.ts, tests/services/events/event.test.ts
fix event page backend changes
=> fix event page backend changes

src/routes/v2/event.ts, src/services/events/event.ts, tests/services/events/event.test.ts
- new route that gets a users current events
=> get user's current events

.github/workflows/test-pr.yaml, src/routes/v2/event.ts, src/routes/v2/index.ts
- removed auth for get event by id endpoint
=> removed auth for event page

src/schema/v2/database.types.ts, src/services/Event/EventService.ts, tests/services/Event/EventService.test.ts
add blurbs for events, in addition to descriptions
=> Add blurbs

src/schema/v2/database.types.ts, src/services/Payment/PaymentService.ts, src/services/emails/confirmation.ts
- Added function into handleCheckoutSession that automatically adds user to specific event mailing list
- Requires events in DB to have a specific mailing list ID for this to work (staging is using currently one list while prod needs 4 or more depending on # of events)
=> Event mailing list

src/middleware/Session.ts, src/routes/v2/index.ts
- added a supabase middleware that checks that the user is in Supabase Auth
- should only work for the admin account as long as we don't add more users to the auth
Resolves #112
=> added supabase auth token middleware
